FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=fishorwhale
ENV N8N_BASIC_AUTH_PASSWORD=Rnrmf44$
ENV N8N_HOST=n8n-on-railway-production-881e.up.railway.app
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
ENV WEBHOOK_TUNNEL_URL=https://${RAILWAY_STATIC_URL}

EXPOSE 5678
CMD ["n8n"]
